### ISSUE TITLE
Meet WebM Muxer Guidelines

### ISSUE THREAD

**Issue by at-wat** [at-wat/ebml-go#70]
https://www.webmproject.org/docs/container/#muxer-guidelines

> Muxers should treat all guidelines marked SHOULD in this section as MUST. This will foster consistency across WebM files in the real world. 
> 
> - WebM SHOULD contain the SeekHead element.
>   - Reason: Allows the client to know if the file contains a Cues element.
> - WebM files SHOULD include a keyframe-only Cues element.
>   - The Cues element SHOULD contain only video key frames, to decrease the size of the file header.
>   - It is recommended that the Cues element be before any clusters, so that the client can seek to a point in the data that has not yet been downloaded in a single seek operation. Ref: a tool that will put the Cues at the front.
> - All absolute (block + cluster) timecodes MUST be monotonically increasing.
>   - All timecodes are associated with the start time of the block.
> - The TimecodeScale element SHOULD be set to a default of 1.000.000 nanoseconds.
>   - Reason: Allows every cluster to have blocks with positive values up to 32.767 seconds.
> - Key frames SHOULD be placed at the beginning of clusters.
>   - Having key frames at the beginning of clusters should make seeking faster and easier for the client.
> - Audio blocks that contain the video key frame's timecode SHOULD be in the same cluster as the video key frame block.
> - Audio blocks that have same absolute timecode as video blocks SHOULD be written before the video blocks.
> - WebM files MUST only support pixels for the DisplayUnit element.

Valid guilds for streaming:
- [x] Have SeekHead (#79)
- [ ] [recommendation] Place Cues element before any clusters (#75)
  - it depends on the user and placing in front is bit complexed to calculate compared to placing second SeekHead at the end.
- [x] Make timecodes monotonically increasing (#73)
- [x] TimecodeScale element: 1.000.000 nanoseconds.
- [x] Start cluster with key frame (#76)
- [x] Place audio blocks that contain the video key frame's timecode in the same cluster as the video key frame block (#76, #75)
- [x] Place audio blocks that have same absolute timecode as video blocks before the video blocks (#73)
- [x] Support only pixels for the DisplayUnit element
